apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-threat-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-threat-detection
  template:
    metadata:
      labels:
        app: ai-threat-detection
    spec:
      containers:
        - name: ai-threat-detection
          image: 418295714127.dkr.ecr.us-east-1.amazonaws.com/ai-threat-detection:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

